name: CodeScan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '18 12 * * 4'

permissions:
  contents: read

jobs:
  CodeScan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify Java version
        run: |
          echo "JAVA_HOME=${{ steps.setup-java.outputs.path }}"
          java -version
          echo "which java: $(which java)"

      - name: Cache files
        uses: actions/cache@v3
        with:
          path: |
            ~/.sonar
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run Analysis
        uses: codescan-io/codescan-scanner-action@5b2e8c5683ef6a5adc8fa3b7950bb07debccce12
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}
          PATH: ${{ steps.setup-java.outputs.path }}/bin:${{ env.PATH }}
        with:
          login: ${{ secrets.CODESCAN_AUTH_TOKEN }}
          organization: ${{ secrets.CODESCAN_ORGANIZATION_KEY }}
          projectKey: ${{ secrets.CODESCAN_PROJECT_KEY }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: codescan.sarif
